pipeline {
    agent any

    tools {
        nodejs "node" // The name of the NodeJS installation you configured in Jenkins
    }

    stages {
        stage('Install') {
            steps {
                script {
                    
                    sh 'npm install'
                }
            }
        }
        
        stage('Test') {
            steps {
                script {
                    
                    sh 'npm test'
                }
            }
        }

        stage('Build') {
            steps {
                script {
                   
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                   
                    echo 'Deploying...'
                }
            }
        }
    }
}
