pipeline {
    agent any
    environment {
        // Define Docker Hub credentials ID
        DOCKERHUB_CREDENTIALS_ID = 'elkkuelias'
        // Define Docker Hub repository name
        DOCKERHUB_REPO = 'elkkuelias/mlengine'
        // Define Docker image tag
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ElkkuElias/MLEngine.git'
            }
        }
        stage('Setup') {
            steps {
                dir('backend') {
                    bat 'python -m venv .venv'
                    bat '.venv\\Scripts\\activate'
                    bat 'pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend') {
                    // Corrected the activation command for Windows
                    bat '.venv\\Scripts\\activate'
                    bat 'python testRunner.py'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    script {
                        // Build Docker image
                        docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                    }
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                dir('backend') {
                    script {
                        // Push Docker image to Docker Hub
                        docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                            docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            dir('backend') {
                junit 'test-reports/*.xml'
            }
        }
    }
}
