pipeline {
    agent any
    environment {
       // Define Docker Hub credentials ID
        DOCKERHUB_CREDENTIALS_ID = 'elkkuelias'
        // Define Docker Hub repository name
        DOCKERHUB_REPO = 'elkkuelias/mlengine'
        // Define Docker image tag
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {


        stage('Checkout') {
            steps {
               git 'https://github.com/ElkkuElias/MLEngine.git'
            }
        }
        stage('Setup') {
            steps {
                sh 'python -m venv venv'
                sh '. venv/bin/activate'
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Test') {
            steps {
                sh '. venv/bin/activate'
                sh 'python testRunner.py'
            }
        }
        stage('Build Docker Image'){
            steps {
                script {
                    // Build Docker image
                    docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                }
            }
        }
        stage('Push Docker Image'){
            steps {
                script {
                    // Push Docker image to Docker Hub
                    docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                        docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                    }
                }
            }
        }

    }

    post {
        always {
            junit 'test-reports/*.xml'
        }
    }
}
